.Dd $Mdocdate: September 21 2024 $
.Dt CIFRISDOI 1
.Os
.Sh NAME
.Nm cifrisdoi
.Nd convert tsv to json for Cifris Angular website
.Sh SYNOPSIS
.Nm cifrisdoi
.Op Fl c
.Op Ar
.Sh DESCRIPTION
The
.Nm
utility converts tsv yada yada.
.sp
.\" .EQ
.\" delim $$
.\" .EN
.\" For example we can take the $x sup 2 + x + 1$ polynomial on $F sub 2$.
.\" .EQ
.\" F sub 2
.\" .EN
.\" .sp
.\" .EQ
.\" x sup 2 + x + 1 = 0
.\" .EN
